name: docker publish

on: push

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - samtools
          - bwa
          - bcftools
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # TODO: container version tagging
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker/${{ matrix.container }}
          tags: lloydkirk/${{ matrix.container }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

  # TODO: template workflows + their dependencies?
  build-workflow:
    runs-on: ubuntu-latest
    needs: build-base-images
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: docker/workflows/bwa-alignment
          tags: lloydkirk/workflows/bwa-alignment:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
