name: docker publish

on: push

jobs:
  build-tools-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - samtools
          - bwa
          - bcftools
          - emacs
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      # TODO: container version tagging
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: docker/tools/${{ matrix.container }}
          tags: quay.io/lkirk/${{ matrix.container }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

  # # TODO: template workflows + their dependencies?
  # build-workflow:
  #   runs-on: ubuntu-latest
  #   needs: build-tools-images
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     - name: Build and push
  #       id: docker_build
  #       uses: docker/build-push-action@v2
  #       with:
  #         push: false
  #         context: docker/workflows/bwa-alignment
  #         tags: quay.io/lkirk/bwa-alignment:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}

  build-devops-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [haskell-stack]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          context: docker/devops/${{ matrix.container }}
          tags: quay.io/lkirk/${{ matrix.container }}:${{ github.ref_name == 'main' && 'latest' || github.ref_name }}
