name: docker publish

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - samtools
          - bwa
          - bcftools
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # - name: Login to DockerHub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # TODO: container version tagging
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          context: docker/${{ matrix.container }}
          tags: lloydkirk/bio/${{ matrix.container }}:latest

      # TODO: template workflows + their dependencies
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        needs: bwa
        with:
          push: false
          context: docker/bio/workflows/bwa-alignment
          tags: lloydkirk/bio/workflows/bwa-alignment:latest
